# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: 'maven:3.6-jdk-8-openj9'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn -U clean package verify
      - run:
          command: |
            arct_val=`mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.artifactId -q -DforceStdout`
            arct_version=`mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout`
            echo ${arct_val}-${arct_version} >> ./target/version.txt
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target/
  deploy_backend:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: .
      - run:
          name: Export enviranment variable version and create version
          command: |
            jar_name=`cat ./project/target/version.txt`
            version=1.0-`date +"%Y%m%d-%H%M%S"`
            jar_name_version="${version}-${jar_name}"
            aws s3 cp ./target/${jar_name}.jar s3://${AWS_JAR_S3}/${jar_name_version}.jar
            aws elasticbeanstalk create-application-version --application-name digihealth-petclinic --version-label ${version} --source-bundle S3Bucket=${AWS_JAR_S3},S3Key="${jar_name_version}.jar"
            aws elasticbeanstalk update-environment --application-name digihealth-petclinic --environment-name digihealth-19-petclinic-dev --version-label ${version}

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_backend:
          requires:
            - build
