# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      - image: 'maven:3.6-jdk-8-openj9'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn -U clean package verify
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target/
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - attach_workspace:
            at: .
      - aws-s3/copy:
          from: ./target/*.jar
          # spring-petclinic-rest-2.2.5
          to: 's3://tom.niu16'
  deploy_backend:
    docker:
      - image: 'amazon/aws-cli:latest'
    steps:
      - checkout
      - run yum -y install tar
      - attach_workspace:
          at: .
      - run: aws s3 cp ./target/*.jar s3://tom.niu16/my-app-1.jar
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_backend:
          requires:
            - build
