# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  build:
    docker:
      - image: 'maven:3.6-jdk-8-openj9'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn -U clean package verify
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target/
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - attach_workspace:
            at: .
      #- run: mv ./target/spring-petclinic-rest-2.2.5.jar ./target/2020110901-spring-petclinic-rest-2.2.5.jar
      - aws-s3/copy:
          from: ./target/spring-petclinic-rest-2.2.5.jar
          to: 's3://elasticbeanstalk-ap-southeast-2-526394010273/2020110902-spring-petclinic-rest-2.2.5.jar'
  awstest:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          name: Check installed AWS CLI version
          command: |
            which aws
            echo $(aws --version)
            if ! echo "$(aws --version)" | grep -q "(aws-cli/2)"; then
                echo "Version 2 installed successfully."
            else
                echo "Incorrect version installed"
                exit 1
            fi
workflows:
  build_and_deploy:
    jobs:
      - awstest
